default:
  selector: textarea#post
  toolbar: styleselect | bold italic | link image | undo redo | table
  plugins:
    - table
    - emotions
    - image
    - link
    - style

alternate:
  selector: textarea.tinymce
  toolbar: styleselect | bold italic | link image | undo redo | table
  plugins:
    - table
    - emotions
    - style
