default:
  selector: textarea#post
  toolbar: styleselect | bold italic | link image | undo redo | table | uploadimage
  plugins:
    - table
    - emotions
    - image
    - link
    - uploadimage
    - style

alternate:
  selector: textarea.tinymce
  toolbar: styleselect | bold italic | link image | undo redo | table | uploadimage
  plugins:
    - table
    - emotions
    - style
    - uploadimage
